# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.16.3 is version 34
    loaderVersion="[36.1,)"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/MinecraftForge/MinecraftForge/issues"
    license="GPL"

    [[mods]]
      modId="extbackup"
      version="${file.jarVersion}"
      displayName="ExtBackup"
      #updateJSONURL="https://minecraftforge.net/versions.json"
      displayURL="minecraftforge.net"
      #logoFile="assets/examplemod/textures/logo.png"
      credits="I'd like to thank my mother and father."
      authors="jinks"
      description='''
      Lets you craft dirt into diamonds. This is a traditional mod that has existed for eons. It is ancient. The holy Notch created it. Jeb rainbowfied it. Dinnerbone made it upside down. Etc.
      '''

      [[dependencies.extbackup]]
        modId="forge"
        mandatory=true
        versionRange="[36.1,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.extbackup]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.16.5]"
        ordering="NONE"
        side="BOTH"