# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
    modLoader="javafml"
    # A version range to match for said mod loader - for regular FML @Mod it will be the forge version
    # Forge for 1.16.3 is version 34
    loaderVersion="[40,)"
    # A URL to refer people to when problems occur with this mod
    issueTrackerURL="https://github.com/jinks/extbackup/issues"
    license="GPL"

    [[mods]]
      modId="extbackup"
      version="${file.jarVersion}"
      displayName="ExtBackup"
      displayURL="https://github.com/jinks/extbackup"
      #logoFile="assets/examplemod/textures/logo.png"
      credits="LatVianModder, alexbobp, vazkii"
      authors="jinks"
      description='''
      Minimal Minecraft backup mod, relying on external backup tools.
      '''

      [[dependencies.extbackup]]
        modId="forge"
        mandatory=true
        versionRange="[47,)"
        ordering="NONE"
        side="BOTH"

      [[dependencies.extbackup]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"
